// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/specs": {
    params: {};
  };
  "/spendings": {
    params: {};
  };
  "/games-chart": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/specs" | "/spendings" | "/games-chart";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/specs" | "/spendings" | "/games-chart";
  };
  "routes/landing.tsx": {
    id: "routes/landing";
    page: "/";
  };
  "routes/specs.tsx": {
    id: "routes/specs";
    page: "/specs";
  };
  "routes/spendings.tsx": {
    id: "routes/spendings";
    page: "/spendings";
  };
  "routes/games-chart.tsx": {
    id: "routes/games-chart";
    page: "/games-chart";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_layout": typeof import("./app/routes/_layout.tsx");
  "routes/landing": typeof import("./app/routes/landing.tsx");
  "routes/specs": typeof import("./app/routes/specs.tsx");
  "routes/spendings": typeof import("./app/routes/spendings.tsx");
  "routes/games-chart": typeof import("./app/routes/games-chart.tsx");
};